# Generated by Django 5.2.1 on 2025-07-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
