# Generated by Django 5.2.1 on 2025-07-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productcategory_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='variant',
        ),
    ]
